# Deployment Target
platform :ios, '8.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

# Cartage support
install! 'cocoapods',
    :share_schemes_for_development_pods => true


target 'APButton_Example' do
    pod 'APButton', :path => '../'

    target 'APButton_Tests' do
        inherit! :search_paths

        pod 'Quick'
        pod 'Nimble'
        pod 'FBSnapshotTestCase'
        pod 'Nimble-Snapshots'
    end
end


post_install do |installer|
    # Carthage support.
    # It puts `APButton.swift` into public headers so @IBInspectable won't be stripped out.
    additionHeader = installer.pods_project.development_pods['APButton/APButton.swift']
    headersBuildPhase = installer.pods_project.objects.select{ |x| x.class == Xcodeproj::Project::Object::PBXHeadersBuildPhase }[0];
    buildFile = headersBuildPhase.add_file_reference(additionHeader)
    buildFile.settings = { 'ATTRIBUTES' => ['Public']}
end
