# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode12.4

language: swift

cache:
    directories:
     - Carthage
     - Pods\ Project/Pods

before_install:
- Pods\ Project/Scripts/Cocoapods/podInstall.command
- brew install carthage
- Carthage\ Project/Scripts/Carthage/carthageInstallTests.command

script:
- bash checkBuild.command
- pod lib lint
- pod spec lint
