# Deployment Target
platform :ios, '11.0'

# Add pods as frameworks so we could add obj-c and swift 3.0 pods
use_frameworks!

target 'APButton_Example' do
    pod 'APButton', :path => '../'
    pod 'APExtensions', :git => 'https://github.com/APUtils/APExtensions'
end

post_install do |installer|
    # Add podInstall.command and podUpdate.command shell scripts to Pods project
    pods_project = installer.pods_project
    pods_project.new_file "../Scripts/Cocoapods/podInstall.command"
    pods_project.new_file "../Scripts/Cocoapods/podUpdate.command"
    
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings.delete 'IPHONEOS_DEPLOYMENT_TARGET'
      end
    end
end
